/**
 */
package org.lunifera.metamodel.businessprocess.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.bpmn2.Bpmn2Package;
import org.eclipse.bpmn2.DocumentRoot;
import org.eclipse.bpmn2.ExtensionAttributeValue;

import org.eclipse.bpmn2.util.Bpmn2Switch;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.util.FeatureMapUtil;

import org.eclipse.emf.edit.command.CommandParameter;

import org.eclipse.emf.edit.domain.EditingDomain;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.lunifera.metamodel.businessprocess.BusinessprocessFactory;

import org.lunifera.metamodel.businessprocess.util.BusinessprocessAdapterFactory;

import org.lunifera.metamodel.knowledge.KnowledgePackage;
import org.lunifera.metamodel.knowledge.ModelingProject;

import org.lunifera.metamodel.knowledge.util.KnowledgeSwitch;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class BusinessprocessItemProviderAdapterFactory extends BusinessprocessAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public BusinessprocessItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.businessprocess.KnowledgeContainerBusinessProcess} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KnowledgeContainerBusinessProcessItemProvider knowledgeContainerBusinessProcessItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.businessprocess.KnowledgeContainerBusinessProcess}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKnowledgeContainerBusinessProcessAdapter() {
		if (knowledgeContainerBusinessProcessItemProvider == null) {
			knowledgeContainerBusinessProcessItemProvider = new KnowledgeContainerBusinessProcessItemProvider(this);
		}

		return knowledgeContainerBusinessProcessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.businessprocess.ActivityDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivityDefinitionItemProvider activityDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.businessprocess.ActivityDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActivityDefinitionAdapter() {
		if (activityDefinitionItemProvider == null) {
			activityDefinitionItemProvider = new ActivityDefinitionItemProvider(this);
		}

		return activityDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.businessprocess.BusinessProcessDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessProcessDefinitionItemProvider businessProcessDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.businessprocess.BusinessProcessDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessProcessDefinitionAdapter() {
		if (businessProcessDefinitionItemProvider == null) {
			businessProcessDefinitionItemProvider = new BusinessProcessDefinitionItemProvider(this);
		}

		return businessProcessDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.businessprocess.Actor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActorItemProvider actorItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.businessprocess.Actor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActorAdapter() {
		if (actorItemProvider == null) {
			actorItemProvider = new ActorItemProvider(this);
		}

		return actorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.businessprocess.Role} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleItemProvider roleItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.businessprocess.Role}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleAdapter() {
		if (roleItemProvider == null) {
			roleItemProvider = new RoleItemProvider(this);
		}

		return roleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.businessprocess.RulesServer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RulesServerItemProvider rulesServerItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.businessprocess.RulesServer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRulesServerAdapter() {
		if (rulesServerItemProvider == null) {
			rulesServerItemProvider = new RulesServerItemProvider(this);
		}

		return rulesServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.businessprocess.HumanTaskServer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HumanTaskServerItemProvider humanTaskServerItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.businessprocess.HumanTaskServer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHumanTaskServerAdapter() {
		if (humanTaskServerItemProvider == null) {
			humanTaskServerItemProvider = new HumanTaskServerItemProvider(this);
		}

		return humanTaskServerItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (knowledgeContainerBusinessProcessItemProvider != null) knowledgeContainerBusinessProcessItemProvider.dispose();
		if (activityDefinitionItemProvider != null) activityDefinitionItemProvider.dispose();
		if (businessProcessDefinitionItemProvider != null) businessProcessDefinitionItemProvider.dispose();
		if (actorItemProvider != null) actorItemProvider.dispose();
		if (roleItemProvider != null) roleItemProvider.dispose();
		if (rulesServerItemProvider != null) rulesServerItemProvider.dispose();
		if (humanTaskServerItemProvider != null) humanTaskServerItemProvider.dispose();
	}

	/**
	 * A child creation extender for the {@link Bpmn2Package}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static class Bpmn2ChildCreationExtender implements IChildCreationExtender {
		/**
		 * The switch for creating child descriptors specific to each extended class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		protected static class CreationSwitch extends Bpmn2Switch<Object> {
			/**
			 * The child descriptors being populated.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected List<Object> newChildDescriptors;

			/**
			 * The domain in which to create the children.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected EditingDomain editingDomain;

			/**
			 * Creates the a switch for populating child descriptors in the given domain.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
				this.newChildDescriptors = newChildDescriptors;
				this.editingDomain = editingDomain;
			}
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object caseDocumentRoot(DocumentRoot object) {
				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
						 BusinessprocessFactory.eINSTANCE.createKnowledgeContainerBusinessProcess()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
						 BusinessprocessFactory.eINSTANCE.createActivityDefinition()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
						 BusinessprocessFactory.eINSTANCE.createBusinessProcessDefinition()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
						 BusinessprocessFactory.eINSTANCE.createActor()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
						 BusinessprocessFactory.eINSTANCE.createRole()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
						 BusinessprocessFactory.eINSTANCE.createRulesServer()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
						 BusinessprocessFactory.eINSTANCE.createHumanTaskServer()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
						 BusinessprocessFactory.eINSTANCE.createKnowledgeContainerBusinessProcess()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
						 BusinessprocessFactory.eINSTANCE.createActivityDefinition()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
						 BusinessprocessFactory.eINSTANCE.createBusinessProcessDefinition()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
						 BusinessprocessFactory.eINSTANCE.createActor()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
						 BusinessprocessFactory.eINSTANCE.createRole()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
						 BusinessprocessFactory.eINSTANCE.createRulesServer()));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
						 BusinessprocessFactory.eINSTANCE.createHumanTaskServer()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object caseExtensionAttributeValue(ExtensionAttributeValue object) {
				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
							 BusinessprocessFactory.eINSTANCE.createKnowledgeContainerBusinessProcess())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
							 BusinessprocessFactory.eINSTANCE.createActivityDefinition())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
							 BusinessprocessFactory.eINSTANCE.createBusinessProcessDefinition())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
							 BusinessprocessFactory.eINSTANCE.createActor())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
							 BusinessprocessFactory.eINSTANCE.createRole())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
							 BusinessprocessFactory.eINSTANCE.createRulesServer())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__SCRIPT,
							 BusinessprocessFactory.eINSTANCE.createHumanTaskServer())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
							 BusinessprocessFactory.eINSTANCE.createKnowledgeContainerBusinessProcess())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
							 BusinessprocessFactory.eINSTANCE.createActivityDefinition())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
							 BusinessprocessFactory.eINSTANCE.createBusinessProcessDefinition())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
							 BusinessprocessFactory.eINSTANCE.createActor())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
							 BusinessprocessFactory.eINSTANCE.createRole())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
							 BusinessprocessFactory.eINSTANCE.createRulesServer())));

				newChildDescriptors.add
					(createChildParameter
						(Bpmn2Package.Literals.EXTENSION_ATTRIBUTE_VALUE__VALUE,
						 FeatureMapUtil.createEntry
							(Bpmn2Package.Literals.DOCUMENT_ROOT__TEXT,
							 BusinessprocessFactory.eINSTANCE.createHumanTaskServer())));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected CommandParameter createChildParameter(Object feature, Object child) {
				return new CommandParameter(null, feature, child);
			}

		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
			ArrayList<Object> result = new ArrayList<Object>();
		   new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
		   return result;
		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public ResourceLocator getResourceLocator() {
			return Luniferabusiness_processmodelEditPlugin.INSTANCE;
		}
	}

	/**
	 * A child creation extender for the {@link KnowledgePackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static class KnowledgeChildCreationExtender implements IChildCreationExtender {
		/**
		 * The switch for creating child descriptors specific to each extended class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		protected static class CreationSwitch extends KnowledgeSwitch<Object> {
			/**
			 * The child descriptors being populated.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected List<Object> newChildDescriptors;

			/**
			 * The domain in which to create the children.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected EditingDomain editingDomain;

			/**
			 * Creates the a switch for populating child descriptors in the given domain.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
				this.newChildDescriptors = newChildDescriptors;
				this.editingDomain = editingDomain;
			}
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object caseModelingProject(ModelingProject object) {
				newChildDescriptors.add
					(createChildParameter
						(KnowledgePackage.Literals.MODELING_PROJECT__KNOWLEDGE_CONTAINERS,
						 BusinessprocessFactory.eINSTANCE.createKnowledgeContainerBusinessProcess()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected CommandParameter createChildParameter(Object feature, Object child) {
				return new CommandParameter(null, feature, child);
			}

		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
			ArrayList<Object> result = new ArrayList<Object>();
		   new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
		   return result;
		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public ResourceLocator getResourceLocator() {
			return Luniferabusiness_processmodelEditPlugin.INSTANCE;
		}
	}

}
