/*
 * generated by Xtext
 */
package org.lunifera.metamodel.dsl.jpa.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JpaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.lunifera.metamodel.dsl.jpa.ui.internal.JpaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.lunifera.metamodel.dsl.jpa.ui.internal.JpaActivator.getInstance().getInjector("org.lunifera.metamodel.dsl.jpa.Jpa");
	}
	
}
