/*
 * generated by Xtext
 */
package org.lunifera.metamodel.dsl.entity.ui.contentassist;


/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class EntityProposalProvider extends AbstractEntityProposalProvider {

}
