/*
* generated by Xtext
*/
package org.lunifera.metamodel.dsl.organization.en.ui.contentassist;

import org.lunifera.metamodel.dsl.organization.en.ui.contentassist.AbstractOrganizationDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class OrganizationDslProposalProvider extends AbstractOrganizationDslProposalProvider {

}
