/*******************************************************************************
 * Copyright (c) 2011, 2012 Cristiano Gavião - Lunifera.org.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Cristiano Gavião - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.lunifera.metamodel.dsl.organization.en.formatting;

import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.lunifera.metamodel.dsl.organization.en.services.OrganizationDslGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class OrganizationDslFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		OrganizationDslGrammarAccess gac = (OrganizationDslGrammarAccess) getGrammarAccess();

		c.setAutoLinewrap(80);
		
		c.setLinewrap(0, 1, 2).before(gac.getSL_COMMENTRule());
		c.setLinewrap(2, 2, 3).before(gac.getML_COMMENTRule());
		c.setLinewrap(1, 1, 2).after(gac.getML_COMMENTRule());
		
		for (Keyword curlyBracket : gac.findKeywords("{", "}")) {
			c.setLinewrap().around(curlyBracket);
		}
		
		c.setLinewrap(1, 1, 2).before(gac.getOrganizationAccess().getCodeKeyword_0_0());
		c.setLinewrap(1, 1, 2).before(gac.getOrganizationAccess().getDescriptionKeyword_1_1_0());
		c.setLinewrap(1, 1, 2).before(gac.getOrganizationAccess().getNameKeyword_1_0_0());
	
		// OrganizationUnit
		c.setLinewrap(2, 2, 3).before(gac.getOrganizationUnitSetAccess().getUnitsKeyword_1());
		c.setIndentation(gac.getOrganizationUnitSetAccess().getLeftCurlyBracketKeyword_2(),
				gac.getOrganizationUnitSetAccess().getRightCurlyBracketKeyword_5());
		
		c.setIndentation(gac.getOrganizationUnitAccess().getLeftCurlyBracketKeyword_4_0(),
				gac.getOrganizationUnitAccess().getRightCurlyBracketKeyword_4_2());
		c.setLinewrap(2, 2, 3).before(gac.getOrganizationUnitAccess().getUnitKeyword_1());
		c.setLinewrap(1, 1, 2).before(gac.getOrganizationUnitAccess().getNameKeyword_4_1_1_0());
		c.setLinewrap(1, 1, 2).before(gac.getOrganizationUnitAccess().getParentKeyword_4_1_0_0());
		c.setLinewrap(1, 1, 2).before(gac.getOrganizationUnitAccess().getDescriptionKeyword_4_1_2_0());		
		
		// Person
		c.setLinewrap(2, 2, 3).before(gac.getPersonSetAccess().getPeopleKeyword_1());
		c.setIndentation(gac.getPersonSetAccess().getLeftCurlyBracketKeyword_2(),
				gac.getPersonSetAccess().getRightCurlyBracketKeyword_5());
		
		c.setIndentation(gac.getPersonAccess().getLeftCurlyBracketKeyword_4_0(),
				gac.getPersonAccess().getRightCurlyBracketKeyword_4_2());
		c.setLinewrap(2, 2, 3).before(gac.getPersonAccess().getPersonKeyword_1());
		c.setLinewrap(1, 1, 2).before(gac.getPersonAccess().getFirstNameKeyword_4_1_0_0());
		c.setLinewrap(1, 1, 2).before(gac.getPersonAccess().getEmailKeyword_4_1_3_0());
		c.setLinewrap(1, 1, 2).before(gac.getPersonAccess().getLastNameKeyword_4_1_2_0());
		c.setLinewrap(1, 1, 2).before(gac.getPersonAccess().getMiddleNameKeyword_4_1_1_0());
		
		// BusinessRole
		c.setLinewrap(2, 2, 3).before(gac.getRoleSetAccess().getBusinessRolesKeyword_1());
		c.setIndentation(gac.getRoleSetAccess().getLeftCurlyBracketKeyword_2(),
				gac.getRoleSetAccess().getRightCurlyBracketKeyword_5());

		
		c.setIndentation(gac.getBusinessRoleAccess().getLeftCurlyBracketKeyword_4_0(),
				gac.getBusinessRoleAccess().getRightCurlyBracketKeyword_4_3());
		c.setLinewrap(2, 2, 3).before(gac.getBusinessRoleAccess().getRoleKeyword_1());
		c.setLinewrap(1, 1, 2).before(gac.getBusinessRoleAccess().getDescriptionKeyword_4_2_0());
		c.setLinewrap(1, 1, 2).before(gac.getBusinessRoleAccess().getNameKeyword_4_1_0());
		
				
		// Worker
		c.setLinewrap(2, 2, 3).before(gac.getWorkerSetAccess().getWorkersKeyword_1());
		c.setIndentation(gac.getWorkerSetAccess().getLeftCurlyBracketKeyword_2(),
				gac.getWorkerSetAccess().getRightCurlyBracketKeyword_5());

		
		c.setIndentation(gac.getWorkerAccess().getLeftCurlyBracketKeyword_4_0(),
				gac.getWorkerAccess().getRightCurlyBracketKeyword_4_2());
		
		c.setLinewrap(2, 2, 3).before(gac.getWorkerAccess().getWorkerKeyword_1());
		c.setLinewrap(1, 1, 2).before(gac.getWorkerAccess().getAllocatedOnKeyword_4_1_0_0());
		c.setLinewrap(1, 1, 2).before(gac.getWorkerAccess().getPlayRolesKeyword_4_1_1_0());
				
		// Partnership
		c.setLinewrap(2, 2, 3).before(gac.getPartnershipSetAccess().getPartnershipsKeyword_1());
		c.setIndentation(gac.getPartnershipSetAccess().getLeftCurlyBracketKeyword_2(),
				gac.getPartnershipSetAccess().getRightCurlyBracketKeyword_5());

		
		c.setIndentation(gac.getPartnershipAccess().getLeftCurlyBracketKeyword_4_0(),
				gac.getPartnershipAccess().getRightCurlyBracketKeyword_4_3());
		
		c.setLinewrap(2, 2, 3).before(gac.getPartnershipAccess().getPartnershipKeyword_1());
		c.setLinewrap(1, 1, 2).before(gac.getPartnershipAccess().getAgreementKeyword_4_2_0());
		c.setLinewrap(1, 1, 2).before(gac.getPartnershipAccess().getResponsibleKeyword_4_1_0());		
	}
}
