/*
 * generated by Xtext
 */
package org.lunifera.metamodel.dsl.entity;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityRuntimeModule extends org.lunifera.metamodel.dsl.entity.AbstractEntityRuntimeModule {

}
