/*******************************************************************************
 * Copyright (c) 2011, 2012 Cristiano Gavião - Lunifera.org.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Cristiano Gavião - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.lunifera.metamodel.dsl.software.composition;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.lunifera.metamodel.dsl.component.template.library.utils.ComponentTemplateLibraryDslModelUtility;
import org.lunifera.metamodel.dsl.software.composition.naming.CompositionDslQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class CompositeModelDslRuntimeModule
		extends
		org.lunifera.metamodel.dsl.software.composition.AbstractCompositeModelDslRuntimeModule {

	@org.eclipse.xtext.service.SingletonBinding(eager = true)
	public Class<? extends ComponentTemplateLibraryDslModelUtility> bindComponentTemplateUtilitiesService() {
		return ComponentTemplateLibraryDslModelUtility.class;
	}

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {

		return CompositionDslQualifiedNameProvider.class;
	}
}
