/*
 * generated by Xtext
 */
package org.lunifera.metamodel.dsl.software.topology.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SoftwareTopologyDslUiModule extends org.lunifera.metamodel.dsl.software.topology.ui.AbstractSoftwareTopologyDslUiModule {
	public SoftwareTopologyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
