/**
 */
package org.lunifera.metamodel.behavior.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.edit.command.CommandParameter;

import org.eclipse.emf.edit.domain.EditingDomain;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.lunifera.metamodel.behavior.BehaviorFactory;

import org.lunifera.metamodel.behavior.util.BehaviorAdapterFactory;

import org.lunifera.metamodel.knowledge.KnowledgePackage;
import org.lunifera.metamodel.knowledge.ModelingProject;

import org.lunifera.metamodel.knowledge.util.KnowledgeSwitch;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class BehaviorItemProviderAdapterFactory extends BehaviorAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public BehaviorItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.KnowledgeContainerBehavior} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KnowledgeContainerBehaviorItemProvider knowledgeContainerBehaviorItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.KnowledgeContainerBehavior}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKnowledgeContainerBehaviorAdapter() {
		if (knowledgeContainerBehaviorItemProvider == null) {
			knowledgeContainerBehaviorItemProvider = new KnowledgeContainerBehaviorItemProvider(this);
		}

		return knowledgeContainerBehaviorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.StepsLibrary} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StepsLibraryItemProvider stepsLibraryItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.StepsLibrary}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStepsLibraryAdapter() {
		if (stepsLibraryItemProvider == null) {
			stepsLibraryItemProvider = new StepsLibraryItemProvider(this);
		}

		return stepsLibraryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.BehaviorBook} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BehaviorBookItemProvider behaviorBookItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.BehaviorBook}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBehaviorBookAdapter() {
		if (behaviorBookItemProvider == null) {
			behaviorBookItemProvider = new BehaviorBookItemProvider(this);
		}

		return behaviorBookItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.EmbedderDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmbedderDefinitionItemProvider embedderDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.EmbedderDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmbedderDefinitionAdapter() {
		if (embedderDefinitionItemProvider == null) {
			embedderDefinitionItemProvider = new EmbedderDefinitionItemProvider(this);
		}

		return embedderDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.StepsImplementationClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StepsImplementationClassItemProvider stepsImplementationClassItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.StepsImplementationClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStepsImplementationClassAdapter() {
		if (stepsImplementationClassItemProvider == null) {
			stepsImplementationClassItemProvider = new StepsImplementationClassItemProvider(this);
		}

		return stepsImplementationClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.Story} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StoryItemProvider storyItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.Story}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStoryAdapter() {
		if (storyItemProvider == null) {
			storyItemProvider = new StoryItemProvider(this);
		}

		return storyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.Meta} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetaItemProvider metaItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.Meta}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetaAdapter() {
		if (metaItemProvider == null) {
			metaItemProvider = new MetaItemProvider(this);
		}

		return metaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.MetaProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetaPropertyItemProvider metaPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.MetaProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetaPropertyAdapter() {
		if (metaPropertyItemProvider == null) {
			metaPropertyItemProvider = new MetaPropertyItemProvider(this);
		}

		return metaPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.Narrative} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NarrativeItemProvider narrativeItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.Narrative}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNarrativeAdapter() {
		if (narrativeItemProvider == null) {
			narrativeItemProvider = new NarrativeItemProvider(this);
		}

		return narrativeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.InOrderTo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InOrderToItemProvider inOrderToItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.InOrderTo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInOrderToAdapter() {
		if (inOrderToItemProvider == null) {
			inOrderToItemProvider = new InOrderToItemProvider(this);
		}

		return inOrderToItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.AsA} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AsAItemProvider asAItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.AsA}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAsAAdapter() {
		if (asAItemProvider == null) {
			asAItemProvider = new AsAItemProvider(this);
		}

		return asAItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.IWantTo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IWantToItemProvider iWantToItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.IWantTo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIWantToAdapter() {
		if (iWantToItemProvider == null) {
			iWantToItemProvider = new IWantToItemProvider(this);
		}

		return iWantToItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.Scenario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScenarioItemProvider scenarioItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.Scenario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScenarioAdapter() {
		if (scenarioItemProvider == null) {
			scenarioItemProvider = new ScenarioItemProvider(this);
		}

		return scenarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.GivenStories} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GivenStoriesItemProvider givenStoriesItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.GivenStories}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGivenStoriesAdapter() {
		if (givenStoriesItemProvider == null) {
			givenStoriesItemProvider = new GivenStoriesItemProvider(this);
		}

		return givenStoriesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.StoryPath} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StoryPathItemProvider storyPathItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.StoryPath}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStoryPathAdapter() {
		if (storyPathItemProvider == null) {
			storyPathItemProvider = new StoryPathItemProvider(this);
		}

		return storyPathItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ExamplesTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExamplesTableItemProvider examplesTableItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ExamplesTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExamplesTableAdapter() {
		if (examplesTableItemProvider == null) {
			examplesTableItemProvider = new ExamplesTableItemProvider(this);
		}

		return examplesTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ExamplesTableRow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExamplesTableRowItemProvider examplesTableRowItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ExamplesTableRow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExamplesTableRowAdapter() {
		if (examplesTableRowItemProvider == null) {
			examplesTableRowItemProvider = new ExamplesTableRowItemProvider(this);
		}

		return examplesTableRowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ExamplesTableHeader} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExamplesTableHeaderItemProvider examplesTableHeaderItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ExamplesTableHeader}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExamplesTableHeaderAdapter() {
		if (examplesTableHeaderItemProvider == null) {
			examplesTableHeaderItemProvider = new ExamplesTableHeaderItemProvider(this);
		}

		return examplesTableHeaderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ExampleTableCell} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExampleTableCellItemProvider exampleTableCellItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ExampleTableCell}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExampleTableCellAdapter() {
		if (exampleTableCellItemProvider == null) {
			exampleTableCellItemProvider = new ExampleTableCellItemProvider(this);
		}

		return exampleTableCellItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.StepSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StepSentenceItemProvider stepSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.StepSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStepSentenceAdapter() {
		if (stepSentenceItemProvider == null) {
			stepSentenceItemProvider = new StepSentenceItemProvider(this);
		}

		return stepSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ActionSentence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionSentenceItemProvider actionSentenceItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ActionSentence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionSentenceAdapter() {
		if (actionSentenceItemProvider == null) {
			actionSentenceItemProvider = new ActionSentenceItemProvider(this);
		}

		return actionSentenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.Context} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContextItemProvider contextItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.Context}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContextAdapter() {
		if (contextItemProvider == null) {
			contextItemProvider = new ContextItemProvider(this);
		}

		return contextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.Expectation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpectationItemProvider expectationItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.Expectation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpectationAdapter() {
		if (expectationItemProvider == null) {
			expectationItemProvider = new ExpectationItemProvider(this);
		}

		return expectationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.And} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AndItemProvider andItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.And}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAndAdapter() {
		if (andItemProvider == null) {
			andItemProvider = new AndItemProvider(this);
		}

		return andItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.Given} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GivenItemProvider givenItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.Given}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGivenAdapter() {
		if (givenItemProvider == null) {
			givenItemProvider = new GivenItemProvider(this);
		}

		return givenItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.When} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WhenItemProvider whenItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.When}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhenAdapter() {
		if (whenItemProvider == null) {
			whenItemProvider = new WhenItemProvider(this);
		}

		return whenItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.Then} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThenItemProvider thenItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.Then}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThenAdapter() {
		if (thenItemProvider == null) {
			thenItemProvider = new ThenItemProvider(this);
		}

		return thenItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.StepLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StepLinkItemProvider stepLinkItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.StepLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStepLinkAdapter() {
		if (stepLinkItemProvider == null) {
			stepLinkItemProvider = new StepLinkItemProvider(this);
		}

		return stepLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.GivenLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GivenLinkItemProvider givenLinkItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.GivenLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGivenLinkAdapter() {
		if (givenLinkItemProvider == null) {
			givenLinkItemProvider = new GivenLinkItemProvider(this);
		}

		return givenLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.WhenLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WhenLinkItemProvider whenLinkItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.WhenLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhenLinkAdapter() {
		if (whenLinkItemProvider == null) {
			whenLinkItemProvider = new WhenLinkItemProvider(this);
		}

		return whenLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ThenLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThenLinkItemProvider thenLinkItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ThenLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThenLinkAdapter() {
		if (thenLinkItemProvider == null) {
			thenLinkItemProvider = new ThenLinkItemProvider(this);
		}

		return thenLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.AndLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AndLinkItemProvider andLinkItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.AndLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAndLinkAdapter() {
		if (andLinkItemProvider == null) {
			andLinkItemProvider = new AndLinkItemProvider(this);
		}

		return andLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.StorySource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StorySourceItemProvider storySourceItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.StorySource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStorySourceAdapter() {
		if (storySourceItemProvider == null) {
			storySourceItemProvider = new StorySourceItemProvider(this);
		}

		return storySourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.StepParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StepParameterItemProvider stepParameterItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.StepParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStepParameterAdapter() {
		if (stepParameterItemProvider == null) {
			stepParameterItemProvider = new StepParameterItemProvider(this);
		}

		return stepParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.StepParameterKey} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StepParameterKeyItemProvider stepParameterKeyItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.StepParameterKey}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStepParameterKeyAdapter() {
		if (stepParameterKeyItemProvider == null) {
			stepParameterKeyItemProvider = new StepParameterKeyItemProvider(this);
		}

		return stepParameterKeyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ExamplesTableIgnorableSeparator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExamplesTableIgnorableSeparatorItemProvider examplesTableIgnorableSeparatorItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ExamplesTableIgnorableSeparator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExamplesTableIgnorableSeparatorAdapter() {
		if (examplesTableIgnorableSeparatorItemProvider == null) {
			examplesTableIgnorableSeparatorItemProvider = new ExamplesTableIgnorableSeparatorItemProvider(this);
		}

		return examplesTableIgnorableSeparatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ExamplesTableColumnSeparator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExamplesTableColumnSeparatorItemProvider examplesTableColumnSeparatorItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ExamplesTableColumnSeparator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExamplesTableColumnSeparatorAdapter() {
		if (examplesTableColumnSeparatorItemProvider == null) {
			examplesTableColumnSeparatorItemProvider = new ExamplesTableColumnSeparatorItemProvider(this);
		}

		return examplesTableColumnSeparatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ExamplesTableValueSeparator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExamplesTableValueSeparatorItemProvider examplesTableValueSeparatorItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ExamplesTableValueSeparator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExamplesTableValueSeparatorAdapter() {
		if (examplesTableValueSeparatorItemProvider == null) {
			examplesTableValueSeparatorItemProvider = new ExamplesTableValueSeparatorItemProvider(this);
		}

		return examplesTableValueSeparatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.lunifera.metamodel.behavior.ExamplesTableHeaderSeparator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExamplesTableHeaderSeparatorItemProvider examplesTableHeaderSeparatorItemProvider;

	/**
	 * This creates an adapter for a {@link org.lunifera.metamodel.behavior.ExamplesTableHeaderSeparator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExamplesTableHeaderSeparatorAdapter() {
		if (examplesTableHeaderSeparatorItemProvider == null) {
			examplesTableHeaderSeparatorItemProvider = new ExamplesTableHeaderSeparatorItemProvider(this);
		}

		return examplesTableHeaderSeparatorItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (knowledgeContainerBehaviorItemProvider != null) knowledgeContainerBehaviorItemProvider.dispose();
		if (stepsLibraryItemProvider != null) stepsLibraryItemProvider.dispose();
		if (behaviorBookItemProvider != null) behaviorBookItemProvider.dispose();
		if (embedderDefinitionItemProvider != null) embedderDefinitionItemProvider.dispose();
		if (stepsImplementationClassItemProvider != null) stepsImplementationClassItemProvider.dispose();
		if (storyItemProvider != null) storyItemProvider.dispose();
		if (metaItemProvider != null) metaItemProvider.dispose();
		if (metaPropertyItemProvider != null) metaPropertyItemProvider.dispose();
		if (narrativeItemProvider != null) narrativeItemProvider.dispose();
		if (inOrderToItemProvider != null) inOrderToItemProvider.dispose();
		if (asAItemProvider != null) asAItemProvider.dispose();
		if (iWantToItemProvider != null) iWantToItemProvider.dispose();
		if (scenarioItemProvider != null) scenarioItemProvider.dispose();
		if (givenStoriesItemProvider != null) givenStoriesItemProvider.dispose();
		if (storyPathItemProvider != null) storyPathItemProvider.dispose();
		if (examplesTableItemProvider != null) examplesTableItemProvider.dispose();
		if (examplesTableRowItemProvider != null) examplesTableRowItemProvider.dispose();
		if (examplesTableHeaderItemProvider != null) examplesTableHeaderItemProvider.dispose();
		if (exampleTableCellItemProvider != null) exampleTableCellItemProvider.dispose();
		if (stepSentenceItemProvider != null) stepSentenceItemProvider.dispose();
		if (actionSentenceItemProvider != null) actionSentenceItemProvider.dispose();
		if (contextItemProvider != null) contextItemProvider.dispose();
		if (expectationItemProvider != null) expectationItemProvider.dispose();
		if (andItemProvider != null) andItemProvider.dispose();
		if (givenItemProvider != null) givenItemProvider.dispose();
		if (whenItemProvider != null) whenItemProvider.dispose();
		if (thenItemProvider != null) thenItemProvider.dispose();
		if (stepLinkItemProvider != null) stepLinkItemProvider.dispose();
		if (givenLinkItemProvider != null) givenLinkItemProvider.dispose();
		if (whenLinkItemProvider != null) whenLinkItemProvider.dispose();
		if (thenLinkItemProvider != null) thenLinkItemProvider.dispose();
		if (andLinkItemProvider != null) andLinkItemProvider.dispose();
		if (storySourceItemProvider != null) storySourceItemProvider.dispose();
		if (stepParameterItemProvider != null) stepParameterItemProvider.dispose();
		if (stepParameterKeyItemProvider != null) stepParameterKeyItemProvider.dispose();
		if (examplesTableIgnorableSeparatorItemProvider != null) examplesTableIgnorableSeparatorItemProvider.dispose();
		if (examplesTableColumnSeparatorItemProvider != null) examplesTableColumnSeparatorItemProvider.dispose();
		if (examplesTableValueSeparatorItemProvider != null) examplesTableValueSeparatorItemProvider.dispose();
		if (examplesTableHeaderSeparatorItemProvider != null) examplesTableHeaderSeparatorItemProvider.dispose();
	}

	/**
	 * A child creation extender for the {@link KnowledgePackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static class KnowledgeChildCreationExtender implements IChildCreationExtender {
		/**
		 * The switch for creating child descriptors specific to each extended class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		protected static class CreationSwitch extends KnowledgeSwitch<Object> {
			/**
			 * The child descriptors being populated.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected List<Object> newChildDescriptors;

			/**
			 * The domain in which to create the children.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected EditingDomain editingDomain;

			/**
			 * Creates the a switch for populating child descriptors in the given domain.
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			CreationSwitch(List<Object> newChildDescriptors, EditingDomain editingDomain) {
				this.newChildDescriptors = newChildDescriptors;
				this.editingDomain = editingDomain;
			}
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			@Override
			public Object caseModelingProject(ModelingProject object) {
				newChildDescriptors.add
					(createChildParameter
						(KnowledgePackage.Literals.MODELING_PROJECT__KNOWLEDGE_CONTAINERS,
						 BehaviorFactory.eINSTANCE.createKnowledgeContainerBehavior()));

				return null;
			}
 
			/**
			 * <!-- begin-user-doc -->
			 * <!-- end-user-doc -->
			 * @generated
			 */
			protected CommandParameter createChildParameter(Object feature, Object child) {
				return new CommandParameter(null, feature, child);
			}

		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public Collection<Object> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
			ArrayList<Object> result = new ArrayList<Object>();
		   new CreationSwitch(result, editingDomain).doSwitch((EObject)object);
		   return result;
		}

		/**
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		public ResourceLocator getResourceLocator() {
			return LuniferabehaviormodelEditPlugin.INSTANCE;
		}
	}

}
