/*
* generated by Xtext
*/
package org.lunifera.metamodel.dsl.jpa.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JpaOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
