/*******************************************************************************
 * Copyright (c) 2011, 2012 Cristiano Gavião - Lunifera.org.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Cristiano Gavião - initial API and implementation
 *******************************************************************************/
/*
* generated by Xtext
*/
package org.lunifera.metamodel.dsl.behavior.stories.en.ui.contentassist;

import org.lunifera.metamodel.dsl.behavior.stories.en.ui.contentassist.AbstractStoryDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class StoryDslProposalProvider extends AbstractStoryDslProposalProvider {

}
