/*
* generated by Xtext
*/
package org.lunifera.metamodel.dsl.software.topology.ui.contentassist;

import org.lunifera.metamodel.dsl.software.topology.ui.contentassist.AbstractSoftwareTopologyDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SoftwareTopologyDslProposalProvider extends AbstractSoftwareTopologyDslProposalProvider {

}
