/*
* generated by Xtext
*/
package org.lunifera.metamodel.dsl.jpa.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JpaProposalProvider extends AbstractJpaProposalProvider {

}
